package com.delivery.domain;

import static com.delivery.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryAllPropertiesEquals(Delivery expected, Delivery actual) {
        assertDeliveryAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryAllUpdatablePropertiesEquals(Delivery expected, Delivery actual) {
        assertDeliveryUpdatableFieldsEquals(expected, actual);
        assertDeliveryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryAutoGeneratedPropertiesEquals(Delivery expected, Delivery actual) {
        assertThat(actual)
            .as("Verify Delivery auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryUpdatableFieldsEquals(Delivery expected, Delivery actual) {
        assertThat(actual)
            .as("Verify Delivery relevant properties")
            .satisfies(a -> assertThat(a.getDeliveryDate()).as("check deliveryDate").isEqualTo(expected.getDeliveryDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a ->
                assertThat(a.getPaidAmount())
                    .as("check paidAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPaidAmount())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryUpdatableRelationshipsEquals(Delivery expected, Delivery actual) {
        assertThat(actual)
            .as("Verify Delivery relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getDriver()).as("check driver").isEqualTo(expected.getDriver()));
    }
}
