package com.delivery.domain;

import static com.delivery.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryItemAllPropertiesEquals(DeliveryItem expected, DeliveryItem actual) {
        assertDeliveryItemAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryItemAllUpdatablePropertiesEquals(DeliveryItem expected, DeliveryItem actual) {
        assertDeliveryItemUpdatableFieldsEquals(expected, actual);
        assertDeliveryItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryItemAutoGeneratedPropertiesEquals(DeliveryItem expected, DeliveryItem actual) {
        assertThat(actual)
            .as("Verify DeliveryItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryItemUpdatableFieldsEquals(DeliveryItem expected, DeliveryItem actual) {
        assertThat(actual)
            .as("Verify DeliveryItem relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getTotalPrice())
                    .as("check totalPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryItemUpdatableRelationshipsEquals(DeliveryItem expected, DeliveryItem actual) {
        assertThat(actual)
            .as("Verify DeliveryItem relationships")
            .satisfies(a -> assertThat(a.getDelivery()).as("check delivery").isEqualTo(expected.getDelivery()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
