package com.delivery.domain;

import static com.delivery.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PriceHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriceHistoryAllPropertiesEquals(PriceHistory expected, PriceHistory actual) {
        assertPriceHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPriceHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriceHistoryAllUpdatablePropertiesEquals(PriceHistory expected, PriceHistory actual) {
        assertPriceHistoryUpdatableFieldsEquals(expected, actual);
        assertPriceHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriceHistoryAutoGeneratedPropertiesEquals(PriceHistory expected, PriceHistory actual) {
        assertThat(actual)
            .as("Verify PriceHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriceHistoryUpdatableFieldsEquals(PriceHistory expected, PriceHistory actual) {
        assertThat(actual)
            .as("Verify PriceHistory relevant properties")
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getEffectiveDate()).as("check effectiveDate").isEqualTo(expected.getEffectiveDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriceHistoryUpdatableRelationshipsEquals(PriceHistory expected, PriceHistory actual) {
        assertThat(actual)
            .as("Verify PriceHistory relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
