package com.delivery.domain;

import static com.delivery.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionAllPropertiesEquals(Production expected, Production actual) {
        assertProductionAutoGeneratedPropertiesEquals(expected, actual);
        assertProductionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionAllUpdatablePropertiesEquals(Production expected, Production actual) {
        assertProductionUpdatableFieldsEquals(expected, actual);
        assertProductionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionAutoGeneratedPropertiesEquals(Production expected, Production actual) {
        assertThat(actual)
            .as("Verify Production auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionUpdatableFieldsEquals(Production expected, Production actual) {
        assertThat(actual)
            .as("Verify Production relevant properties")
            .satisfies(a -> assertThat(a.getProductionDate()).as("check productionDate").isEqualTo(expected.getProductionDate()))
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionUpdatableRelationshipsEquals(Production expected, Production actual) {
        assertThat(actual)
            .as("Verify Production relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getProductionSite()).as("check productionSite").isEqualTo(expected.getProductionSite()));
    }
}
