package com.delivery.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductReturnAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReturnAllPropertiesEquals(ProductReturn expected, ProductReturn actual) {
        assertProductReturnAutoGeneratedPropertiesEquals(expected, actual);
        assertProductReturnAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReturnAllUpdatablePropertiesEquals(ProductReturn expected, ProductReturn actual) {
        assertProductReturnUpdatableFieldsEquals(expected, actual);
        assertProductReturnUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReturnAutoGeneratedPropertiesEquals(ProductReturn expected, ProductReturn actual) {
        assertThat(actual)
            .as("Verify ProductReturn auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReturnUpdatableFieldsEquals(ProductReturn expected, ProductReturn actual) {
        assertThat(actual)
            .as("Verify ProductReturn relevant properties")
            .satisfies(a -> assertThat(a.getReturnDate()).as("check returnDate").isEqualTo(expected.getReturnDate()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReturnUpdatableRelationshipsEquals(ProductReturn expected, ProductReturn actual) {
        assertThat(actual)
            .as("Verify ProductReturn relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getDelivery()).as("check delivery").isEqualTo(expected.getDelivery()));
    }
}
