package com.delivery.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductionSiteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionSiteAllPropertiesEquals(ProductionSite expected, ProductionSite actual) {
        assertProductionSiteAutoGeneratedPropertiesEquals(expected, actual);
        assertProductionSiteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionSiteAllUpdatablePropertiesEquals(ProductionSite expected, ProductionSite actual) {
        assertProductionSiteUpdatableFieldsEquals(expected, actual);
        assertProductionSiteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionSiteAutoGeneratedPropertiesEquals(ProductionSite expected, ProductionSite actual) {
        assertThat(actual)
            .as("Verify ProductionSite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionSiteUpdatableFieldsEquals(ProductionSite expected, ProductionSite actual) {
        assertThat(actual)
            .as("Verify ProductionSite relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionSiteUpdatableRelationshipsEquals(ProductionSite expected, ProductionSite actual) {
        assertThat(actual)
            .as("Verify ProductionSite relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
