package com.delivery.domain;

import static com.delivery.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ReturnItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnItemAllPropertiesEquals(ReturnItem expected, ReturnItem actual) {
        assertReturnItemAutoGeneratedPropertiesEquals(expected, actual);
        assertReturnItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnItemAllUpdatablePropertiesEquals(ReturnItem expected, ReturnItem actual) {
        assertReturnItemUpdatableFieldsEquals(expected, actual);
        assertReturnItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnItemAutoGeneratedPropertiesEquals(ReturnItem expected, ReturnItem actual) {
        assertThat(actual)
            .as("Verify ReturnItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnItemUpdatableFieldsEquals(ReturnItem expected, ReturnItem actual) {
        assertThat(actual)
            .as("Verify ReturnItem relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnItemUpdatableRelationshipsEquals(ReturnItem expected, ReturnItem actual) {
        assertThat(actual)
            .as("Verify ReturnItem relationships")
            .satisfies(a -> assertThat(a.getProductReturn()).as("check productReturn").isEqualTo(expected.getProductReturn()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
