package com.delivery.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoundCustomerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoundCustomerAllPropertiesEquals(RoundCustomer expected, RoundCustomer actual) {
        assertRoundCustomerAutoGeneratedPropertiesEquals(expected, actual);
        assertRoundCustomerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoundCustomerAllUpdatablePropertiesEquals(RoundCustomer expected, RoundCustomer actual) {
        assertRoundCustomerUpdatableFieldsEquals(expected, actual);
        assertRoundCustomerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoundCustomerAutoGeneratedPropertiesEquals(RoundCustomer expected, RoundCustomer actual) {
        assertThat(actual)
            .as("Verify RoundCustomer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoundCustomerUpdatableFieldsEquals(RoundCustomer expected, RoundCustomer actual) {
        assertThat(actual)
            .as("Verify RoundCustomer relevant properties")
            .satisfies(a -> assertThat(a.getSequenceOrder()).as("check sequenceOrder").isEqualTo(expected.getSequenceOrder()))
            .satisfies(a -> assertThat(a.getVisited()).as("check visited").isEqualTo(expected.getVisited()))
            .satisfies(a -> assertThat(a.getVisitTime()).as("check visitTime").isEqualTo(expected.getVisitTime()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoundCustomerUpdatableRelationshipsEquals(RoundCustomer expected, RoundCustomer actual) {
        assertThat(actual)
            .as("Verify RoundCustomer relationships")
            .satisfies(a -> assertThat(a.getRound()).as("check round").isEqualTo(expected.getRound()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
