package com.delivery.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSettingsAllPropertiesEquals(TenantSettings expected, TenantSettings actual) {
        assertTenantSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSettingsAllUpdatablePropertiesEquals(TenantSettings expected, TenantSettings actual) {
        assertTenantSettingsUpdatableFieldsEquals(expected, actual);
        assertTenantSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSettingsAutoGeneratedPropertiesEquals(TenantSettings expected, TenantSettings actual) {
        assertThat(actual)
            .as("Verify TenantSettings auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSettingsUpdatableFieldsEquals(TenantSettings expected, TenantSettings actual) {
        assertThat(actual)
            .as("Verify TenantSettings relevant properties")
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getTimezone()).as("check timezone").isEqualTo(expected.getTimezone()))
            .satisfies(a -> assertThat(a.getDateFormat()).as("check dateFormat").isEqualTo(expected.getDateFormat()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantSettingsUpdatableRelationshipsEquals(TenantSettings expected, TenantSettings actual) {
        assertThat(actual)
            .as("Verify TenantSettings relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
